services:
  postgres:
    image: postgres:15-alpine
    container_name: mm-postgres
    restart: unless-stopped
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost
    # روی مک‌های سری M بهتره دیتابیس نیتیو اجرا شه (بدون شبیه‌ساز)
    platform: linux/arm64

  mattermost:
    image: mattermost/mattermost-team-edition:latest
    container_name: mattermost
    restart: unless-stopped
    # این خط برای مک بوک حیاتیه (چون متریمست نسخه ARM نداره)
    platform: linux/amd64
    depends_on:
      - postgres
    ports:
      - "8065:8065"
    volumes:
      - ./volumes/config:/mattermost/config
      - ./volumes/data:/mattermost/data
      - ./volumes/logs:/mattermost/logs
    environment:
      - MM_SQLSETTINGS_DRIVERNAME=postgres
      - MM_SQLSETTINGS_DATASOURCE=postgres://mmuser:mmuser_password@postgres:5432/mattermost?sslmode=disable&connect_timeout=10
      - MM_SERVICESETTINGS_SITEURL=http://localhost:8065

networks:
  default:
    name: mattermost-net